### ISSUE TITLE
how to add a column to layout

### ISSUE THREAD

**Issue by ppeyman** [breezefront/theme-frontend-breeze-evolution#1]
Hi dear 
How Can i Add a layout to the product view page i add custome xml file in layout of my child theme but doesnot change anything 
i change in Configuration > web > defaultsLayout > Default Product Layout --> 3 columns and etc doesnot change. 
and again i added `layout="2columns-right"` to page catalog_view_product or  catalog_view_product_type_simple but doesnot change anything ! 
do you have any solution for it ? 

please help me ! 

![image](https://user-images.githubusercontent.com/13271466/186474058-e25ce5f1-20ab-4440-83aa-7388346e0c40.png)

**Comment by vovayatsyuk** [comment]
Let's solve one problem at a time. How do you exactly trying to change the layout now? Please describe each step you've made (1, 2, 3...).

**Comment by ppeyman** [comment]
I did 3 ways to changed it and add a block or layout

first for example i have a delivery block and i need add it on the **free space**

1) I created an xml file with catalog_view_product_type_simple.xml
2) in xml file i added below code
    ```
<referenceContainer name="sidebar.additional">
        <block class="Magento\Cms\Block\Block" name="delivery_rule_block" before="-">
            <arguments>
                <argument name="block_id" xsi:type="string">delivery_rule_block</argument>
            </arguments>
        </block>
    </referenceContainer>

```

3) and  cleared cache 

not worked Just i need a container there or block to add some information for customers. 


regards

**Comment by vovayatsyuk** [comment]
On your screenshot, I see the breeze-blank theme. Are you sure you've activated your breeze/evolution-based theme?

**Comment by ppeyman** [comment]
> On your screenshot, I see the breeze-blank theme. Are you sure you've activated your breeze/evolution-based theme?

Yes I'm sure
I added in another place of page

**Comment by vovayatsyuk** [comment]
If so, please double-check you've made everything else correctly. For example, your XML file is not correctly named. The correct name will be `catalog_product_view_type_simple.xml`

**Comment by ppeyman** [comment]
> If so, please double-check you've made everything else correctly. For example, your XML file is not correctly named. The correct name will be `catalog_product_view_type_simple.xml`

Because I type fast type wrong xml file name 
I Checked Everything 

theme doesn't works with 3 column i created new container with another name and shown below not beside it 
please watch below pic


![image](https://user-images.githubusercontent.com/13271466/186582098-f7136ea5-db48-4053-a680-2ffd787daa3a.png)

**Comment by vovayatsyuk** [comment]
Just made the `app/design/frontend/Local/breeze-custom/Magento_Catalog/layout/catalog_product_view_type_simple.xml` with the following content:

```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        layout="3columns"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="sidebar.additional">
            <block class="Magento\Cms\Block\Block" name="delivery_rule_block" before="-">
                <arguments>
                    <argument name="block_id" xsi:type="string">delivery_rule_block</argument>
                </arguments>
            </block>
        </referenceContainer>
    </body>
</page>
```

And everything works like expected:

![image](https://user-images.githubusercontent.com/306080/186584053-bb329430-c49e-447f-b8bd-2cf8bdd340d7.png)

**Comment by ppeyman** [comment]
I tried, it didn't work

Did you test on a child theme?


![image](https://user-images.githubusercontent.com/13271466/186596319-7043e35c-573c-455b-925a-ec759bce8d65.png)

**Comment by vovayatsyuk** [comment]
Yes. It's a child theme.

**Comment by vovayatsyuk** [comment]
@ppeyman did you make it to work? If not, you may post a link to your repo or attach a zip file of your custom theme, and will look at why it's not working.

**Comment by websuits** [comment]
Works for me

**Comment by ppeyman** [comment]
> @ppeyman did you make it to work? If not, you may post a link to your repo or attach a zip file of your custom theme, and will look at why it's not working.
thank you dear [vovayatsyuk](https://github.com/vovayatsyuk)


I found my mistake, I must have changed `Design > Layout` to `no layout update`  in the specified product
