### ISSUE TITLE
[Breeze] Page builder crashing totally

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#10]
I am now on the design phase of the static pages. But as i notice there a lot of issues in the page builder editor, everything crashes. You can't drag "Rows" in the editor, slider is not working, you can't add slides, etc.

I find this very critical since Breeze shouldn't affect the admin at all. Is there a way we can have these fixed ?

<img width="1679" alt="Screenshot 2022-09-15 at 23 58 09" src="https://user-images.githubusercontent.com/42982977/190507538-30521771-a5fa-4c6a-815f-294c626ae606.png">

**Comment by vovayatsyuk** [comment]
We do not change anything at the backend. I think you just need to rerun static content deployment.

**Comment by websuits** [comment]
After digging some more about these errors i found that it was related to the upgrades of magento.

This is due to module-page-builder being updated for Magento 2.4.5 but this does not seem to be backwards compatible with 2.4.4 from what I have experienced.

Run composer require magento/module-page-builder:2.2.2 from your Magento root directory to bring the correct version in and I recommend you remove this require when upgrading past 2.4.4.

**Comment by websuits** [comment]
But seems that Swissup EasyBanner is still crashing the preview for it's own block in page builder. 

Error filtering template: Type Error occurred when creating object: Magento\Captcha\Model\Checkout\ConfigProvider, Argument 3 passed to Magento\Captcha\Model\Checkout\ConfigProvider::__construct() must be of the type array, null given, called in /var/www/client.magstart.ro/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
