### ISSUE TITLE
add Layout in account information on frontend doesn't works

### ISSUE THREAD

**Issue by ppeyman** [breezefront/theme-frontend-breeze-evolution#12]
Hi dears 
I want to add a block in account information before save button.
I added below code to **breeze_customer_account_edit.xml**  doesn't works in breeze theme but in luma and another works well 

```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
         <referenceContainer name="form.additional.info">
            <block class="Vendor\Module\Block\Account\Edit\Form" name="module_form_additional_info_customer" template="Vendor_Module::additionalinfocustomer.phtml"/>
        </referenceContainer>
    </body>
</page>
```

please help

**Comment by vovayatsyuk** [comment]
We do not change anything in layout, blocks, templates (except very few things), so everything should work fine. You can check breeze blank theme sources.

But we do change js processing. If your template wants to render uiComponent, it will not work. How’s your template looks like?

**Comment by ppeyman** [comment]
> We do not change anything in layout, blocks, templates (except very few things), so everything should work fine. You can check breeze blank theme sources.
> 
> But we do change js processing. If your template wants to render uiComponent, it will not work. How’s your template looks like?

here is my [file](https://filebin.net/x25tai39olruzy81)

**Comment by vovayatsyuk** [comment]
[Fixed](https://github.com/breezefront/theme-frontend-breeze-blank/commit/f3b4247873d6dcc0b9ea3ef54e6416f0e63e8dad). The block was hidden by css rule.

Thanks for reporting!
