### ISSUE TITLE
Cookie modal showing at every page load

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#13]
Cookie panel shows every time when you refresh the page, and when going to checkout page the cookie policy modal shows again. This was previously reported.

**Comment by vovayatsyuk** [comment]
What’s your swissup/module-breeze version?

Here is the previous report: https://github.com/breezefront/theme-frontend-breeze-evolution/issues/9

**Comment by websuits** [comment]
Hi Vova !

Swissup_Breeze 1.14.4

**Comment by vovayatsyuk** [comment]
That’s strange. Any chance to get the url to your site?

**Comment by websuits** [comment]
https://client.magstart.ro/

**Comment by vovayatsyuk** [comment]
The cookie consent lifetime is set to 0, but the GDPR module doesn't support zero values. Try to set the proper days value in gdpr config: https://docs.swissuplabs.com/m2/extensions/gdpr/configuration/#cookie-consent-section
