### ISSUE TITLE
swatch image, on product page, It does not work properly

### ISSUE THREAD

**Issue by redati** [breezefront/theme-frontend-breeze-evolution#15]
1 - Open a product with swatch image and have more than one image
2 - click on the thumb of a second image from the gallery
3 - select a product option that changes the image

Expected: Larger image is changed according to the chosen product option

it happens: the thumbnail image is changed

xample of a website in production

![11](https://github.com/breezefront/theme-frontend-breeze-evolution/assets/6043222/7a80d0a1-9697-42b4-adf2-4da311c0c3ee)

![22](https://github.com/breezefront/theme-frontend-breeze-evolution/assets/6043222/2b0e1795-093d-4987-96fa-78e120939ef1)

latest magento and breeze.

**Comment by vovayatsyuk** [comment]
Thanks. Fixed this issue with another one in https://github.com/breezefront/module-breeze/commit/06164081dfc1ae071c55fd95ccf2cc22c36bfe02
