### ISSUE TITLE
Cart/minicart login modal not showing when guest checkout is disabled

### ISSUE THREAD

**Issue by cagartner** [breezefront/theme-frontend-breeze-evolution#19]
When the guest checkout options is disabled on admin, the Go to checkout button on minicart and cart page does not work and the login/create account modal is not showing:

Do nothing:
![image](https://github.com/breezefront/theme-frontend-breeze-evolution/assets/4007696/f403d6f7-da2f-410f-81e8-121cc8ffb6d8)

Modal that was supposed to show:
![image](https://github.com/breezefront/theme-frontend-breeze-evolution/assets/4007696/3c2c824c-c560-433f-8279-0eaec0fbff14)

Regards.

**Comment by vovayatsyuk** [comment]
Thanks! Will tag the new version today.
