### ISSUE TITLE
How do you add custom fonts ?

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#2]
I've tried several methods but i don't want to include them in head, can't custom fonts be loaded in traditional Magento methods ?

I always get font files not found

**Comment by vovayatsyuk** [comment]
We haven't used custom fonts in our themes yet so we may improve this to make it easier.

What do you mean by "traditional Magento methods"?

**Comment by websuits** [comment]
Ok, got it, will try to find a way somehow. I meant with font-face and baseDir.

PS: have you heard about compatibility issues, with the other modules from swissup? I’ve opened a ticket but haven’t got any response. Have you tested gdpr consent pop-up or infinite scroll? I had zero luck in making them work but on the docs page it says they are compatible.

**Comment by vovayatsyuk** [comment]
Thanks, I will write a short manual on custom fonts later this week.

Breezefront is a project by swissup, so we trying to integrate all of our modules with breeze :) We will look into your ticket tomorrow (it's a night in our country right now).

**Comment by websuits** [comment]
Of course, have a good night and thanks for the infos. Looking forward for the manual.

**Comment by vovayatsyuk** [comment]
Hi, please take a look at https://breezefront.com/custom-fonts

However, you should update to the latest version (released today) to use this manual.

**Comment by websuits** [comment]
Hi, I've followed your documentation, however unfortunately for me at least it's not working. My files cannot be found. Placed font in :

app/design/frontend/Vendor/child-teme/web/fonts/Poppins/Poppins-Bold.woff2

In app/design/frontend/Vendor/child-teme/web/css/_custom i've included another less files :

@import 'custom/typography/_fonts';

And in _fonts.less i've included the font :

& when (@critical) {
    @font-family__Poppins-Regular: 'Poppins-Regular';

    @font-face {
        font-family: @font-family__Poppins-Regular;
        src: url('../../../fonts/Poppins/Poppins-Bold.woff2') format('truetype');
        font-weight: 700;
        font-style: normal;
        font-display: swap;
    }
}

Also in my _custom.less i've added :

// Typography
// apply new font for all texts:
@base__font-family: 'Poppins-Regular', sans-serif;

// or, apply new font for all block titles:
@block-title__font-family: 'Poppins-Regular', sans-serif;

// or, all hero block titles:
@hero-block-title__font-family: 'Poppins-Regular', sans-serif;

// or, buttons:
@button__font-family: 'Poppins-Regular', sans-serif;

// or, anything else:
& when (@critical) {
    h1 {
        font-family: 'Poppins-Regular', sans-serif;
    }
}

All of these concludes in console error :

GET https://client.website.ro/static/version1662160632/frontend/Vendor/fonts/Poppins/Poppins-Bold.woff2 net::ERR_ABORTED 404

**Comment by vovayatsyuk** [comment]
Try to use one level up “../“ in the less files.

**Comment by websuits** [comment]
Silly me, indeed with only one directory apart it works. 

Thanks @vovayatsyuk !

**Comment by vovayatsyuk** [comment]
Great! 

I’ll add a notice that the relative paths are always applied relative to the “css” folder.
