### ISSUE TITLE
Issue with Category Page Links in Safari on iPhone

### ISSUE THREAD

**Issue by roma84** [breezefront/theme-frontend-breeze-evolution#21]
The links do not respond to clicks on the first attempt; they only work on the second attempt.

Yes, we are experiencing the same issue on the demo site.
https://breeze.swissupdemo.com/breeze_evolution/women/tops-women/jackets-women.html

I'll share a video link with you; please check it out.
https://drive.google.com/file/d/14WvsHD0rPsDYjpLBdQyDDO8oz2sfvC4s/view?usp=sharing

NFQ-12620

**Comment by vovayatsyuk** [comment]
Super strange bug.

When inserting links dynamically using delayed javascript, and **inserted link is outside of the visible area**, Safari does not catch the click on this link **and on the links nearby** from the first try.

I was able to reproduce this issue with this code:

```html
<div id="test"></div>

<script type="text/javascript">
setTimeout(() => {
    $('#test').append('<a onclick="alert(1)">Hello</a>');
}, 2000);
</script>
```

I don't know how to properly fix this issue. For now, I'll use `.hide()` and `.show()` to force Browser to reflow layout.
