### ISSUE TITLE
How can we add a js file to breeze_default ?

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#3]
So what i'm trying to do is i want to add the infinite loading functionality to breeze, so what i've done in my child theme i've create the module folder and the xml file breeze_default.xml where i'm trying to add the js file.

I was thinking something like this would work but it doesn't, or at least not for me, can we have a suggestion for the best approach of adding a js file like this for a module in general ? I guess this would apply for any case.

<img width="289" alt="Screenshot 2022-08-31 at 02 52 23" src="https://user-images.githubusercontent.com/42982977/187563394-960080af-51da-4966-a6b8-de8c32888974.png">
<img width="1101" alt="Screenshot 2022-08-31 at 02 55 40" src="https://user-images.githubusercontent.com/42982977/187563726-070a39c2-5620-44af-a81c-2a058fa8d2e4.png">

**Comment by vovayatsyuk** [comment]
Looks like everything is correct. The only part I'd change is to remove the "path" item as you don't want to change its value.

I just made the same files and scroll.js is included as it should.

My paths are:

```
app/design/frontend/Local/breeze-custom/Swissup_Ajaxlayerednavigation/layout/breeze_default.xml
app/design/frontend/Local/breeze-custom/Swissup_Ajaxlayerednavigation/web/js/breeze/navigation/scroll.js
```
