### ISSUE TITLE
How do you completely override a less file ?

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#4]
I would personally like to override completely a less file from blank or evolution, line _minisearch.less file for example. In order to keep a clean code. Is there a way we can do that at the moment ?

**Comment by websuits** [comment]
Never mind, i found out. Steps :

Create _default.less for overriding theme default less files. By importing the same path from original theme the styling is totally overridden.

**Comment by vovayatsyuk** [comment]
You don't need to override the whole _default.less file. Just copy the file you'd like to override keeping the same file path:

```
app/design/frontend/Local/breeze-custom/web/css/layout/_minisearch.less - overrrides minisearch from blank theme
app/design/frontend/Local/breeze-custom/web/css/theme/layout/_minisearch.less - overrides minisearch from evolution theme
```

**Comment by websuits** [comment]
Thanks!
