### ISSUE TITLE
Custom Scripts functionality

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#6]
According to the documentation if you create web/js/breeze/extend.js you can place some random js code there and it will be available.

<img width="1120" alt="Screenshot 2022-09-12 at 01 02 51" src="https://user-images.githubusercontent.com/42982977/189550703-b12ff0a9-71d4-42fa-b00b-0ba96f31dbf6.png">

From what i've tested so far, that code is not doing anything. Checking exactly the example provided js file is not loaded at all.

**Comment by vovayatsyuk** [comment]
Just fixed the docs. The `()` were missing:

```js
(function () {
    'use strict';

    $(document).on('breeze:load', function () {
        console.log('Hello');
    });
})();
```
