### ISSUE TITLE
How do you override third party module js/less

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#7]
I want for example to override : 
vendor/swissup/module-navigationpro/view/frontend/web/css/source/layout/_orientation-horizontal.less

Can you override js files/components as files or the extend is default Magento with mixins ? I would like for example to override the js file that adds "active" classes on minisearch.

**Comment by vovayatsyuk** [comment]
### LESS

We use the same less compiler as Luma use, so anything that works with the Luma theme should work with the Breeze theme. What did you try to do and what didn't work?

### JS Mixins

Yes, you can create mixins: https://breezefront.com/mixins. Just add `$.mixin('quickSearch', {});` to your custom js file.
As for completely override, I don't see a reason why it shouldn't work either.

**Comment by websuits** [comment]
Thank you, you answered my question, i wanted to remove any doubt that Magento _module functionality would not work like in default.

**Comment by websuits** [comment]
Yes, indeed, i was interested actually in deleting entire less files, so after i've made my _module.less int the Swissup_Navigationpro/web/css/source/_module.less, i removed from there what files i didn't wanted.

Thank you Vova !
