### ISSUE TITLE
[Evolution] Empty mobile categories min-height .column.main

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#8]
Not sure if this is intended but i find this empty space redundant if there are no default messages for empty categories.

<img width="1506" alt="Screenshot 2022-09-12 at 01 13 08" src="https://user-images.githubusercontent.com/42982977/189551021-61477194-59a3-43a6-ac71-66451dca3938.png">

**Comment by vovayatsyuk** [comment]
Made it a bit shorter, but I think it is needed for the empty pages (cart, logged out customer) so the footer would not "touch" the page's text.
