### ISSUE TITLE
[Cookies][Swissup][Revolution] Cookie policy pop-up showing randomly

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#9]
I open my page on incognito and i accept the cookies
I get this in console :
privacy-tools/cookie/accept/ 500

I open my page normally and i receive this in console automatically :
Swissup_Gdpr/js/breeze/cookie-bar.js net::ERR_BLOCKED_BY_CLIENT

**Most important : I navigate to checkout and the cookie pop-up randomly opens.**

All my modules and theme Revolution are up to date to the latest versions.

**Comment by vovayatsyuk** [comment]
Thanks for reporting. Fixed.
